language: erlang
script: "make REBAR=rebar all test"
otp_release:
   - R15B02
   - R15B01
   - R15B
   - R14B04
   - R14B03
   - R14B02
matrix:
  allow_failures:
    - otp_release: R14B04
    - otp_release: R14B03
    - otp_release: R14B02
